(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const l=document.querySelector(".header-form"),f=document.querySelector(".theme-toggle-button"),a=document.querySelector(".tasks-list");document.querySelector(".task-list-item-btn");const c=document.querySelector("body");function g(e){const t=JSON.parse(localStorage.getItem("tasks"))||[];t.push(e),localStorage.setItem("tasks",JSON.stringify(t))}function p(e){const s=(JSON.parse(localStorage.getItem("tasks"))||[]).filter((n,o)=>o!==e);localStorage.setItem("tasks",JSON.stringify(s))}function h(){const t=(JSON.parse(localStorage.getItem("tasks"))||[]).map(({title:s,description:n})=>`<li class="task-list-item">
      <button class="task-list-item-btn">Delete</button>
      <h3>${s}</h3>
      <p>${n}</p>
  </li>`).join("");a.insertAdjacentHTML("beforeend",t)}function k(e,t){localStorage.setItem(e,JSON.stringify(t))}function S(e,t=null){const s=localStorage.getItem(e);return s?JSON.parse(s):t}function y({title:e,description:t}){const s=`<li class="task-list-item">
      <button class="task-list-item-btn">Delete</button>
      <h3>${e}</h3>
      <p>${t}</p>
  </li>`;a.insertAdjacentHTML("beforeend",s)}const u="theme";function d(e){const t=e==="light";c.classList.toggle("theme-light",t),c.classList.toggle("theme-dark",!t)}function m(){const e=S(u,"dark");d(e)}f.addEventListener("click",()=>{const t=c.classList.contains("theme-dark")?"light":"dark";d(t),k(u,t)});m();m();h();const L=e=>{e.preventDefault();const t=e.target.taskName.value.trim(),s=e.target.taskDescription.value.trim();if(console.log(t,s),!t||!s){alert("Please write task name and description");return}y({title:t,description:s}),g({title:t,description:s}),l.reset()};l.addEventListener("submit",L);a.addEventListener("click",e=>{if(e.target.classList.contains("task-list-item-btn")){const t=e.target.closest(".task-list-item"),s=[...a.children].indexOf(t);p(s),t.remove()}});
//# sourceMappingURL=index.js.map
